### ISSUE TITLE
Bug: cursor Position

### ISSUE THREAD

**Issue by mtewes** [mtewes/lensingpage#17]
Ich habe mit mehreren Browsern (Safari, Firefox, und Chrome !) das Problem, dass die Position (z.B. der roten Galaxie) wenn ich über die Canvas fahre zu dem Maus-zeiger verschoben ist, besonders wenn ich in der Seite rumscrolle.
Bisher hielt ich das für unwichtig, aber nun habe ich verstanden, dass ich aus genau diesem Grund auch die Probleme beim "scrollen" durch das Struktur-Canvas habe: das horizontale scrollen geht dann nicht mehr, weil die Position des cursors fälschlicherweise über oder unter dem Balken ist!
Somit ist das nun schon ein echt störender Bug.

Ich hoffe, das kann behoben werden, wenn man sich das "erfassen" des Cursors über jedem Canvas noch mal ansieht. Eventuell dort eine art Reset einbauen?

**Comment by mtewes** [comment]
wenn ich den "wheel" eventlistener einfach rausnehme, also scrollX und Y einfach auf 0 lasse (wie unten), geht es bei mir prima und der Bug ist behoben (so ist es nun auch live). @jooel , kannst du dich erinnern, wofür diese scrollX und Y gut waren?

```
var scrollX = 0;
var scrollY = 0;
//document.addEventListener("wheel", (e) =>{ //offset of mouse coordinates due to scrolling
//    scrollX = e.deltaX;
//    scrollY = e.deltaY;
//})
```

**Comment by jooel** [comment]
Wenn ich mich richtig erinnere, trat genau dieser Bug mit der Verschiebung von Mauszeiger zu Galaxie mal bei mir auf, als es noch kein scrollX und scrollY gab. Ich dachte, diese Verschiebung hätte was mit einem Offset wegen des Scrollings auf der Seite zu tun und nachdem ich scrollX und Y implementiert hatte, ist dieser Bug nicht mehr aufgetreten.

Wenn ich jetzt scrollX und Y auf 0 lasse, funktioniert es bei mir auch einwandfrei (in Edge). Wenn das mit den anderen Browsern auch klappt, lassen wir die beiden Variablen ab jetzt einfach auf 0.

**Comment by mtewes** [comment]
Ist mit dem letzten merge behoben, closing.
